name: Run Weather Script ACII

on:
  workflow_dispatch:  # umožní manuálne spustenie

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull marsur64/asci_weather_kosice:15062026


      - name: Run script and output pocasie.txt
        run: |
          docker run --rm marsur64/asci_weather_kosice:15062026 \
          sh -c "/root/1.sh && cat /root/pocasie.txt"
